# Generated by Django 3.1.1 on 2020-09-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('rangoHorarioDesde', models.IntegerField()),
                ('rangoHorarioHasta', models.IntegerField()),
                ('diasAlmacenamientoStream', models.IntegerField()),
                ('canalStream', models.TextField(max_length=100)),
                ('smtpHost', models.TextField(max_length=100)),
                ('smtpUsuario', models.TextField(max_length=100)),
                ('smtpContrasena', models.TextField(max_length=100)),
                ('smtpSecure', models.TextField(max_length=50)),
                ('smtpPuerto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('moduloNumero', models.IntegerField(unique=True)),
                ('moduloDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TextField(max_length=50)),
                ('endTime', models.TextField(max_length=50)),
                ('observation', models.TextField(max_length=2000)),
                ('statusRecord', models.TextField(max_length=50)),
                ('saveVideo', models.CharField(max_length=1)),
                ('obsNameVideo', models.TextField(max_length=200)),
                ('statusUpload', models.CharField(max_length=50)),
                ('dateUpload', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('jaulaNumero', models.IntegerField(unique=True)),
                ('modulo', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='pezInterface.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='CentroDestinatario',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('centro', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='pezInterface.centro')),
            ],
        ),
    ]
